name: "Congressional Latest Videos"
# author: "MettaCode Developers"
# description: "Retrieve latest floor actions from US Congress and create JSON file"

on:
  push:
    branches:
      - main
      # - master

  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron: "*/90 * * * *"

permissions:
  contents: write

jobs:
  save_json_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm install express
      - run: npm install puppeteer
      - name: Run Index.js Javascript
        run: npm run start
        # run: node index.js
      - name: commit-latest-videos-json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Latest Videos JSON Updated
