name: "Congressional Latest Videos"
# author: "MettaCode Developers"
# description: "Retrieve latest floor actions from US Congress and create JSON file"

on:
  push:
    branches:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/90 * * * *"

permissions:
  contents: write

jobs:
  save_json_file:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      # - uses: actions/checkout@v2
      - name: Checkout
        # uses: actions/checkout@v3
        uses: actions/checkout@v4
        # with:
        #   sparse-checkout: |
        #     latest_videos.json
        #   sparse-checkout-cone-mode: false
      - name: Get Version
        run: node --version
      - run: npm --version
      - run: npm install
      - name: Install express
        run: npm install express
      - name: Install puppeteer
        run: npm install puppeteer
      - name: Install fs
        run: npm install fs
      - name: run-javascript
        # run: node index.js
        run: npm run start
      - name: commit-latest-videos-json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Latest Videos JSON Updated
